// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v6.33.4
// source: gno/tm2/crypto/merkle.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

/** messages */
export interface ProofOp {
  type: string;
  key: Uint8Array;
  data: Uint8Array;
}

export interface Proof {
  ops: ProofOp[];
}

export interface SimpleProof {
  total: bigint;
  index: bigint;
  leafHash: Uint8Array;
  aunts: Uint8Array[];
}

export interface SimpleProofNode {
  hash: Uint8Array;
  parent?: SimpleProofNode | undefined;
  left?: SimpleProofNode | undefined;
  right?: SimpleProofNode | undefined;
}

export interface MERKLEBytesList {
  Value: Uint8Array[];
}

function createBaseProofOp(): ProofOp {
  return { type: "", key: new Uint8Array(0), data: new Uint8Array(0) };
}

export const ProofOp: MessageFns<ProofOp> = {
  encode(message: ProofOp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.key.length !== 0) {
      writer.uint32(18).bytes(message.key);
    }
    if (message.data.length !== 0) {
      writer.uint32(26).bytes(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProofOp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseProofOp();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.type = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.key = reader.bytes();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.data = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ProofOp {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      key: isSet(object.key) ? bytesFromBase64(object.key) : new Uint8Array(0),
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
    };
  },

  toJSON(message: ProofOp): unknown {
    const obj: any = {};
    if (message.type !== undefined) {
      obj.type = message.type;
    }
    if (message.key !== undefined) {
      obj.key = base64FromBytes(message.key);
    }
    if (message.data !== undefined) {
      obj.data = base64FromBytes(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProofOp>, I>>(base?: I): ProofOp {
    return ProofOp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProofOp>, I>>(object: I): ProofOp {
    const message = createBaseProofOp();
    message.type = object.type ?? "";
    message.key = object.key ?? new Uint8Array(0);
    message.data = object.data ?? new Uint8Array(0);
    return message;
  },
};

function createBaseProof(): Proof {
  return { ops: [] };
}

export const Proof: MessageFns<Proof> = {
  encode(message: Proof, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.ops) {
      ProofOp.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Proof {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseProof();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.ops.push(ProofOp.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Proof {
    return { ops: globalThis.Array.isArray(object?.ops) ? object.ops.map((e: any) => ProofOp.fromJSON(e)) : [] };
  },

  toJSON(message: Proof): unknown {
    const obj: any = {};
    if (message.ops?.length) {
      obj.ops = message.ops.map((e) => ProofOp.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Proof>, I>>(base?: I): Proof {
    return Proof.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Proof>, I>>(object: I): Proof {
    const message = createBaseProof();
    message.ops = object.ops?.map((e) => ProofOp.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSimpleProof(): SimpleProof {
  return { total: 0n, index: 0n, leafHash: new Uint8Array(0), aunts: [] };
}

export const SimpleProof: MessageFns<SimpleProof> = {
  encode(message: SimpleProof, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.total !== 0n) {
      if (BigInt.asIntN(64, message.total) !== message.total) {
        throw new globalThis.Error("value provided for field message.total of type sint64 too large");
      }
      writer.uint32(8).sint64(message.total);
    }
    if (message.index !== 0n) {
      if (BigInt.asIntN(64, message.index) !== message.index) {
        throw new globalThis.Error("value provided for field message.index of type sint64 too large");
      }
      writer.uint32(16).sint64(message.index);
    }
    if (message.leafHash.length !== 0) {
      writer.uint32(26).bytes(message.leafHash);
    }
    for (const v of message.aunts) {
      writer.uint32(34).bytes(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SimpleProof {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSimpleProof();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.total = reader.sint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.index = reader.sint64() as bigint;
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.leafHash = reader.bytes();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.aunts.push(reader.bytes());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): SimpleProof {
    return {
      total: isSet(object.total) ? BigInt(object.total) : 0n,
      index: isSet(object.index) ? BigInt(object.index) : 0n,
      leafHash: isSet(object.leafHash)
        ? bytesFromBase64(object.leafHash)
        : isSet(object.leaf_hash)
        ? bytesFromBase64(object.leaf_hash)
        : new Uint8Array(0),
      aunts: globalThis.Array.isArray(object?.aunts) ? object.aunts.map((e: any) => bytesFromBase64(e)) : [],
    };
  },

  toJSON(message: SimpleProof): unknown {
    const obj: any = {};
    if (message.total !== undefined) {
      obj.total = message.total.toString();
    }
    if (message.index !== undefined) {
      obj.index = message.index.toString();
    }
    if (message.leafHash !== undefined) {
      obj.leafHash = base64FromBytes(message.leafHash);
    }
    if (message.aunts?.length) {
      obj.aunts = message.aunts.map((e) => base64FromBytes(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SimpleProof>, I>>(base?: I): SimpleProof {
    return SimpleProof.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SimpleProof>, I>>(object: I): SimpleProof {
    const message = createBaseSimpleProof();
    message.total = (object.total !== undefined && object.total !== null) ? BigInt(object.total) : 0n;
    message.index = (object.index !== undefined && object.index !== null) ? BigInt(object.index) : 0n;
    message.leafHash = object.leafHash ?? new Uint8Array(0);
    message.aunts = object.aunts?.map((e) => e) || [];
    return message;
  },
};

function createBaseSimpleProofNode(): SimpleProofNode {
  return { hash: new Uint8Array(0), parent: undefined, left: undefined, right: undefined };
}

export const SimpleProofNode: MessageFns<SimpleProofNode> = {
  encode(message: SimpleProofNode, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hash.length !== 0) {
      writer.uint32(10).bytes(message.hash);
    }
    if (message.parent !== undefined) {
      SimpleProofNode.encode(message.parent, writer.uint32(18).fork()).join();
    }
    if (message.left !== undefined) {
      SimpleProofNode.encode(message.left, writer.uint32(26).fork()).join();
    }
    if (message.right !== undefined) {
      SimpleProofNode.encode(message.right, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SimpleProofNode {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSimpleProofNode();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.hash = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.parent = SimpleProofNode.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.left = SimpleProofNode.decode(reader, reader.uint32());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.right = SimpleProofNode.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): SimpleProofNode {
    return {
      hash: isSet(object.Hash)
        ? bytesFromBase64(object.Hash)
        : isSet(object.hash)
        ? bytesFromBase64(object.hash)
        : new Uint8Array(0),
      parent: isSet(object.Parent)
        ? SimpleProofNode.fromJSON(object.Parent)
        : isSet(object.parent)
        ? SimpleProofNode.fromJSON(object.parent)
        : undefined,
      left: isSet(object.Left)
        ? SimpleProofNode.fromJSON(object.Left)
        : isSet(object.left)
        ? SimpleProofNode.fromJSON(object.left)
        : undefined,
      right: isSet(object.Right)
        ? SimpleProofNode.fromJSON(object.Right)
        : isSet(object.right)
        ? SimpleProofNode.fromJSON(object.right)
        : undefined,
    };
  },

  toJSON(message: SimpleProofNode): unknown {
    const obj: any = {};
    if (message.hash !== undefined) {
      obj.Hash = base64FromBytes(message.hash);
    }
    if (message.parent !== undefined) {
      obj.Parent = SimpleProofNode.toJSON(message.parent);
    }
    if (message.left !== undefined) {
      obj.Left = SimpleProofNode.toJSON(message.left);
    }
    if (message.right !== undefined) {
      obj.Right = SimpleProofNode.toJSON(message.right);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SimpleProofNode>, I>>(base?: I): SimpleProofNode {
    return SimpleProofNode.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SimpleProofNode>, I>>(object: I): SimpleProofNode {
    const message = createBaseSimpleProofNode();
    message.hash = object.hash ?? new Uint8Array(0);
    message.parent = (object.parent !== undefined && object.parent !== null)
      ? SimpleProofNode.fromPartial(object.parent)
      : undefined;
    message.left = (object.left !== undefined && object.left !== null)
      ? SimpleProofNode.fromPartial(object.left)
      : undefined;
    message.right = (object.right !== undefined && object.right !== null)
      ? SimpleProofNode.fromPartial(object.right)
      : undefined;
    return message;
  },
};

function createBaseMERKLEBytesList(): MERKLEBytesList {
  return { Value: [] };
}

export const MERKLEBytesList: MessageFns<MERKLEBytesList> = {
  encode(message: MERKLEBytesList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.Value) {
      writer.uint32(10).bytes(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MERKLEBytesList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMERKLEBytesList();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.Value.push(reader.bytes());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MERKLEBytesList {
    return { Value: globalThis.Array.isArray(object?.Value) ? object.Value.map((e: any) => bytesFromBase64(e)) : [] };
  },

  toJSON(message: MERKLEBytesList): unknown {
    const obj: any = {};
    if (message.Value?.length) {
      obj.Value = message.Value.map((e) => base64FromBytes(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MERKLEBytesList>, I>>(base?: I): MERKLEBytesList {
    return MERKLEBytesList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MERKLEBytesList>, I>>(object: I): MERKLEBytesList {
    const message = createBaseMERKLEBytesList();
    message.Value = object.Value?.map((e) => e) || [];
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

type DeepPartial<T> = T extends bigint ? string | number | bigint
  : T extends Builtin ? T : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
