// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v6.33.4
// source: gno/gno/auth/auth.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Any } from "../../../google/protobuf/any.js";

/**
 * MsgCreateSession creates a new account session,
 * denoted as "m_create_session"
 */
export interface MsgCreateSession {
  /** the bech32 address of the session creator */
  creator: string;
  /** the session public key wrapped as a TM2 pubkey Any */
  sessionKey?:
    | Any
    | undefined;
  /** unix timestamp expiry, or 0 for no expiry */
  expiresAt: bigint;
  /** allowed realm paths, or empty for unrestricted paths */
  allowPaths: string[];
  /** spending limit ("<amount><denomination>"), or empty for no spending */
  spendLimit: string;
  /** spending period in seconds, or 0 for lifetime cap */
  spendPeriod: bigint;
}

/**
 * MsgRevokeSession revokes an existing account session,
 * denoted as "m_revoke_session"
 */
export interface MsgRevokeSession {
  /** the bech32 address of the session creator */
  creator: string;
  /** the session public key wrapped as a TM2 pubkey Any */
  sessionKey?: Any | undefined;
}

/**
 * MsgRevokeAllSessions revokes all sessions for the creator,
 * denoted as "m_revoke_all_sessions"
 */
export interface MsgRevokeAllSessions {
  /** the bech32 address of the session creator */
  creator: string;
}

function createBaseMsgCreateSession(): MsgCreateSession {
  return { creator: "", sessionKey: undefined, expiresAt: 0n, allowPaths: [], spendLimit: "", spendPeriod: 0n };
}

export const MsgCreateSession: MessageFns<MsgCreateSession> = {
  encode(message: MsgCreateSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.sessionKey !== undefined) {
      Any.encode(message.sessionKey, writer.uint32(18).fork()).join();
    }
    if (message.expiresAt !== 0n) {
      if (BigInt.asIntN(64, message.expiresAt) !== message.expiresAt) {
        throw new globalThis.Error("value provided for field message.expiresAt of type sint64 too large");
      }
      writer.uint32(24).sint64(message.expiresAt);
    }
    for (const v of message.allowPaths) {
      writer.uint32(34).string(v!);
    }
    if (message.spendLimit !== "") {
      writer.uint32(42).string(message.spendLimit);
    }
    if (message.spendPeriod !== 0n) {
      if (BigInt.asIntN(64, message.spendPeriod) !== message.spendPeriod) {
        throw new globalThis.Error("value provided for field message.spendPeriod of type sint64 too large");
      }
      writer.uint32(48).sint64(message.spendPeriod);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgCreateSession();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.creator = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.sessionKey = Any.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.expiresAt = reader.sint64() as bigint;
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.allowPaths.push(reader.string());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.spendLimit = reader.string();
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.spendPeriod = reader.sint64() as bigint;
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgCreateSession {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      sessionKey: isSet(object.sessionKey)
        ? Any.fromJSON(object.sessionKey)
        : isSet(object.session_key)
        ? Any.fromJSON(object.session_key)
        : undefined,
      expiresAt: isSet(object.expiresAt)
        ? BigInt(object.expiresAt)
        : isSet(object.expires_at)
        ? BigInt(object.expires_at)
        : 0n,
      allowPaths: globalThis.Array.isArray(object?.allowPaths)
        ? object.allowPaths.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.allow_paths)
        ? object.allow_paths.map((e: any) => globalThis.String(e))
        : [],
      spendLimit: isSet(object.spendLimit)
        ? globalThis.String(object.spendLimit)
        : isSet(object.spend_limit)
        ? globalThis.String(object.spend_limit)
        : "",
      spendPeriod: isSet(object.spendPeriod)
        ? BigInt(object.spendPeriod)
        : isSet(object.spend_period)
        ? BigInt(object.spend_period)
        : 0n,
    };
  },

  toJSON(message: MsgCreateSession): unknown {
    const obj: any = {};
    if (message.creator !== undefined) {
      obj.creator = message.creator;
    }
    if (message.sessionKey !== undefined) {
      obj.sessionKey = Any.toJSON(message.sessionKey);
    }
    if (message.expiresAt !== undefined) {
      obj.expiresAt = message.expiresAt.toString();
    }
    if (message.allowPaths?.length) {
      obj.allowPaths = message.allowPaths;
    }
    if (message.spendLimit !== undefined) {
      obj.spendLimit = message.spendLimit;
    }
    if (message.spendPeriod !== undefined) {
      obj.spendPeriod = message.spendPeriod.toString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateSession>, I>>(base?: I): MsgCreateSession {
    return MsgCreateSession.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateSession>, I>>(object: I): MsgCreateSession {
    const message = createBaseMsgCreateSession();
    message.creator = object.creator ?? "";
    message.sessionKey = (object.sessionKey !== undefined && object.sessionKey !== null)
      ? Any.fromPartial(object.sessionKey)
      : undefined;
    message.expiresAt = (object.expiresAt !== undefined && object.expiresAt !== null) ? BigInt(object.expiresAt) : 0n;
    message.allowPaths = object.allowPaths?.map((e) => e) || [];
    message.spendLimit = object.spendLimit ?? "";
    message.spendPeriod = (object.spendPeriod !== undefined && object.spendPeriod !== null)
      ? BigInt(object.spendPeriod)
      : 0n;
    return message;
  },
};

function createBaseMsgRevokeSession(): MsgRevokeSession {
  return { creator: "", sessionKey: undefined };
}

export const MsgRevokeSession: MessageFns<MsgRevokeSession> = {
  encode(message: MsgRevokeSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.sessionKey !== undefined) {
      Any.encode(message.sessionKey, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRevokeSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgRevokeSession();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.creator = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.sessionKey = Any.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgRevokeSession {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      sessionKey: isSet(object.sessionKey)
        ? Any.fromJSON(object.sessionKey)
        : isSet(object.session_key)
        ? Any.fromJSON(object.session_key)
        : undefined,
    };
  },

  toJSON(message: MsgRevokeSession): unknown {
    const obj: any = {};
    if (message.creator !== undefined) {
      obj.creator = message.creator;
    }
    if (message.sessionKey !== undefined) {
      obj.sessionKey = Any.toJSON(message.sessionKey);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRevokeSession>, I>>(base?: I): MsgRevokeSession {
    return MsgRevokeSession.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRevokeSession>, I>>(object: I): MsgRevokeSession {
    const message = createBaseMsgRevokeSession();
    message.creator = object.creator ?? "";
    message.sessionKey = (object.sessionKey !== undefined && object.sessionKey !== null)
      ? Any.fromPartial(object.sessionKey)
      : undefined;
    return message;
  },
};

function createBaseMsgRevokeAllSessions(): MsgRevokeAllSessions {
  return { creator: "" };
}

export const MsgRevokeAllSessions: MessageFns<MsgRevokeAllSessions> = {
  encode(message: MsgRevokeAllSessions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRevokeAllSessions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgRevokeAllSessions();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.creator = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgRevokeAllSessions {
    return { creator: isSet(object.creator) ? globalThis.String(object.creator) : "" };
  },

  toJSON(message: MsgRevokeAllSessions): unknown {
    const obj: any = {};
    if (message.creator !== undefined) {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRevokeAllSessions>, I>>(base?: I): MsgRevokeAllSessions {
    return MsgRevokeAllSessions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRevokeAllSessions>, I>>(object: I): MsgRevokeAllSessions {
    const message = createBaseMsgRevokeAllSessions();
    message.creator = object.creator ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

type DeepPartial<T> = T extends bigint ? string | number | bigint
  : T extends Builtin ? T : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
