// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v6.33.4
// source: ibc/lightclients/gno/v1/gno.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ProofSpec } from "../../../../cosmos/ics23/v1/proofs.js";
import { Duration } from "../../../../google/protobuf/duration.js";
import { Timestamp } from "../../../../google/protobuf/timestamp.js";
import { PublicKey } from "../../../../tendermint/crypto/keys.js";
import { Height } from "../../../core/client/v1/client.js";
import { MerkleRoot } from "../../../core/commitment/v1/commitment.js";

/**
 * ClientState from Gno tracks the current validator set, latest height,
 * and a possible frozen height.
 */
export interface ClientState {
  chainId: string;
  trustLevel?:
    | Fraction
    | undefined;
  /**
   * duration of the period since the LatestTimestamp during which the
   * submitted headers are valid for upgrade
   */
  trustingPeriod?:
    | Duration
    | undefined;
  /** duration of the staking unbonding period */
  unbondingPeriod?:
    | Duration
    | undefined;
  /** defines how much new (untrusted) header's Time can drift into the future. */
  maxClockDrift?:
    | Duration
    | undefined;
  /** Block height when the client was frozen due to a misbehaviour */
  frozenHeight?:
    | Height
    | undefined;
  /** Latest height the client was updated to */
  latestHeight?:
    | Height
    | undefined;
  /** Proof specifications used in verifying counterparty state */
  proofSpecs: ProofSpec[];
  /**
   * Path at which next upgraded client will be committed.
   * Each element corresponds to the key for a single CommitmentProof in the
   * chained proof. NOTE: ClientState must stored under
   * `{upgradePath}/{upgradeHeight}/clientState` ConsensusState must be stored
   * under `{upgradepath}/{upgradeHeight}/consensusState` For SDK chains using
   * the default upgrade module, upgrade_path should be []string{"upgrade",
   * "upgradedIBCState"}`
   */
  upgradePath: string[];
  /**
   * allow_update_after_expiry is deprecated
   *
   * @deprecated
   */
  allowUpdateAfterExpiry: boolean;
  /**
   * allow_update_after_misbehaviour is deprecated
   *
   * @deprecated
   */
  allowUpdateAfterMisbehaviour: boolean;
  /**
   * In order to distinguisgh between Gno and Tendermint light clients
   * we add a client type field. This is useful for clients that
   * may support multiple light client types.
   */
  lcType: string;
}

/** ConsensusState defines the consensus state from Gno. */
export interface ConsensusState {
  /**
   * timestamp that corresponds to the block height in which the ConsensusState
   * was stored.
   */
  timestamp?:
    | Timestamp
    | undefined;
  /** commitment root (i.e app hash) */
  root?: MerkleRoot | undefined;
  nextValidatorsHash: Uint8Array;
  /**
   * In order to distinguisgh between Gno and Tendermint light clients
   * we add a client type field. This is useful for clients that
   * may support multiple light client types.
   */
  lcType: string;
}

/**
 * Misbehaviour is a wrapper over two conflicting Headers
 * that implements Misbehaviour interface expected by ICS-02
 */
export interface Misbehaviour {
  /**
   * ClientID is deprecated
   *
   * @deprecated
   */
  clientId: string;
  header1?: Header | undefined;
  header2?: Header | undefined;
}

/**
 * Header defines the Tendermint client consensus Header.
 * It encapsulates all the information necessary to update from a trusted
 * Tendermint ConsensusState. The inclusion of TrustedHeight and
 * TrustedValidators allows this update to process correctly, so long as the
 * ConsensusState for the TrustedHeight exists, this removes race conditions
 * among relayers The SignedHeader and ValidatorSet are the new untrusted update
 * fields for the client. The TrustedHeight is the height of a stored
 * ConsensusState on the client that will be used to verify the new untrusted
 * header. The Trusted ConsensusState must be within the unbonding period of
 * current time in order to correctly verify, and the TrustedValidators must
 * hash to TrustedConsensusState.NextValidatorsHash since that is the last
 * trusted validator set at the TrustedHeight.
 */
export interface Header {
  signedHeader?: SignedHeader | undefined;
  validatorSet?: ValidatorSet | undefined;
  trustedHeight?: Height | undefined;
  trustedValidators?: ValidatorSet | undefined;
}

export interface Block {
  header?: GnoHeader | undefined;
  data?: Data | undefined;
  lastCommit?: Commit | undefined;
}

export interface GnoHeader {
  version: string;
  chainId: string;
  height: bigint;
  time?: Timestamp | undefined;
  numTxs: bigint;
  totalTxs: bigint;
  appVersion: string;
  lastBlockId?: BlockID | undefined;
  lastCommitHash: Uint8Array;
  dataHash: Uint8Array;
  validatorsHash: Uint8Array;
  nextValidatorsHash: Uint8Array;
  consensusHash: Uint8Array;
  appHash: Uint8Array;
  lastResultsHash: Uint8Array;
  proposerAddress: string;
}

export interface Data {
  txs: Uint8Array[];
}

export interface Commit {
  blockId?: BlockID | undefined;
  precommits: CommitSig[];
}

export interface BlockID {
  hash: Uint8Array;
  partsHeader?: PartSetHeader | undefined;
}

export interface SignedHeader {
  header?: GnoHeader | undefined;
  commit?: Commit | undefined;
}

export interface LightBlock {
  signedHeader?: SignedHeader | undefined;
  validatorSet?: ValidatorSet | undefined;
}

export interface CommitSig {
  type: number;
  height: bigint;
  round: bigint;
  blockId?: BlockID | undefined;
  timestamp?: Timestamp | undefined;
  validatorAddress: string;
  validatorIndex: bigint;
  signature: Uint8Array;
}

/**
 * Vote represents a prevote, precommit, or commit vote from validators for
 * consensus.
 */
export interface Vote {
  type: number;
  height: bigint;
  round: bigint;
  blockId?: BlockID | undefined;
  timestamp?: Timestamp | undefined;
  validatorAddress: string;
  validatorIndex: bigint;
  signature: Uint8Array;
}

export interface PartSet {
}

export interface PartSetHeader {
  total: bigint;
  hash: Uint8Array;
}

export interface Validator {
  address: string;
  pubKey?: PublicKey | undefined;
  votingPower: bigint;
  proposerPriority: bigint;
}

export interface ValidatorSet {
  validators: Validator[];
  proposer?: Validator | undefined;
}

/**
 * Fraction defines the protobuf message type for tmmath.Fraction that only
 * supports positive values.
 */
export interface Fraction {
  numerator: bigint;
  denominator: bigint;
}

function createBaseClientState(): ClientState {
  return {
    chainId: "",
    trustLevel: undefined,
    trustingPeriod: undefined,
    unbondingPeriod: undefined,
    maxClockDrift: undefined,
    frozenHeight: undefined,
    latestHeight: undefined,
    proofSpecs: [],
    upgradePath: [],
    allowUpdateAfterExpiry: false,
    allowUpdateAfterMisbehaviour: false,
    lcType: "",
  };
}

export const ClientState: MessageFns<ClientState> = {
  encode(message: ClientState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chainId !== "") {
      writer.uint32(10).string(message.chainId);
    }
    if (message.trustLevel !== undefined) {
      Fraction.encode(message.trustLevel, writer.uint32(18).fork()).join();
    }
    if (message.trustingPeriod !== undefined) {
      Duration.encode(message.trustingPeriod, writer.uint32(26).fork()).join();
    }
    if (message.unbondingPeriod !== undefined) {
      Duration.encode(message.unbondingPeriod, writer.uint32(34).fork()).join();
    }
    if (message.maxClockDrift !== undefined) {
      Duration.encode(message.maxClockDrift, writer.uint32(42).fork()).join();
    }
    if (message.frozenHeight !== undefined) {
      Height.encode(message.frozenHeight, writer.uint32(50).fork()).join();
    }
    if (message.latestHeight !== undefined) {
      Height.encode(message.latestHeight, writer.uint32(58).fork()).join();
    }
    for (const v of message.proofSpecs) {
      ProofSpec.encode(v!, writer.uint32(66).fork()).join();
    }
    for (const v of message.upgradePath) {
      writer.uint32(74).string(v!);
    }
    if (message.allowUpdateAfterExpiry !== false) {
      writer.uint32(80).bool(message.allowUpdateAfterExpiry);
    }
    if (message.allowUpdateAfterMisbehaviour !== false) {
      writer.uint32(88).bool(message.allowUpdateAfterMisbehaviour);
    }
    if (message.lcType !== "") {
      writer.uint32(98).string(message.lcType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseClientState();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.chainId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.trustLevel = Fraction.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.trustingPeriod = Duration.decode(reader, reader.uint32());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.unbondingPeriod = Duration.decode(reader, reader.uint32());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.maxClockDrift = Duration.decode(reader, reader.uint32());
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.frozenHeight = Height.decode(reader, reader.uint32());
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.latestHeight = Height.decode(reader, reader.uint32());
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.proofSpecs.push(ProofSpec.decode(reader, reader.uint32()));
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.upgradePath.push(reader.string());
            continue;
          }
          case 10: {
            if (tag !== 80) {
              break;
            }

            message.allowUpdateAfterExpiry = reader.bool();
            continue;
          }
          case 11: {
            if (tag !== 88) {
              break;
            }

            message.allowUpdateAfterMisbehaviour = reader.bool();
            continue;
          }
          case 12: {
            if (tag !== 98) {
              break;
            }

            message.lcType = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ClientState {
    return {
      chainId: isSet(object.chainId)
        ? globalThis.String(object.chainId)
        : isSet(object.chain_id)
        ? globalThis.String(object.chain_id)
        : "",
      trustLevel: isSet(object.trustLevel)
        ? Fraction.fromJSON(object.trustLevel)
        : isSet(object.trust_level)
        ? Fraction.fromJSON(object.trust_level)
        : undefined,
      trustingPeriod: isSet(object.trustingPeriod)
        ? Duration.fromJSON(object.trustingPeriod)
        : isSet(object.trusting_period)
        ? Duration.fromJSON(object.trusting_period)
        : undefined,
      unbondingPeriod: isSet(object.unbondingPeriod)
        ? Duration.fromJSON(object.unbondingPeriod)
        : isSet(object.unbonding_period)
        ? Duration.fromJSON(object.unbonding_period)
        : undefined,
      maxClockDrift: isSet(object.maxClockDrift)
        ? Duration.fromJSON(object.maxClockDrift)
        : isSet(object.max_clock_drift)
        ? Duration.fromJSON(object.max_clock_drift)
        : undefined,
      frozenHeight: isSet(object.frozenHeight)
        ? Height.fromJSON(object.frozenHeight)
        : isSet(object.frozen_height)
        ? Height.fromJSON(object.frozen_height)
        : undefined,
      latestHeight: isSet(object.latestHeight)
        ? Height.fromJSON(object.latestHeight)
        : isSet(object.latest_height)
        ? Height.fromJSON(object.latest_height)
        : undefined,
      proofSpecs: globalThis.Array.isArray(object?.proofSpecs)
        ? object.proofSpecs.map((e: any) => ProofSpec.fromJSON(e))
        : globalThis.Array.isArray(object?.proof_specs)
        ? object.proof_specs.map((e: any) => ProofSpec.fromJSON(e))
        : [],
      upgradePath: globalThis.Array.isArray(object?.upgradePath)
        ? object.upgradePath.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.upgrade_path)
        ? object.upgrade_path.map((e: any) => globalThis.String(e))
        : [],
      allowUpdateAfterExpiry: isSet(object.allowUpdateAfterExpiry)
        ? globalThis.Boolean(object.allowUpdateAfterExpiry)
        : isSet(object.allow_update_after_expiry)
        ? globalThis.Boolean(object.allow_update_after_expiry)
        : false,
      allowUpdateAfterMisbehaviour: isSet(object.allowUpdateAfterMisbehaviour)
        ? globalThis.Boolean(object.allowUpdateAfterMisbehaviour)
        : isSet(object.allow_update_after_misbehaviour)
        ? globalThis.Boolean(object.allow_update_after_misbehaviour)
        : false,
      lcType: isSet(object.lcType)
        ? globalThis.String(object.lcType)
        : isSet(object.lc_type)
        ? globalThis.String(object.lc_type)
        : "",
    };
  },

  toJSON(message: ClientState): unknown {
    const obj: any = {};
    if (message.chainId !== undefined) {
      obj.chainId = message.chainId;
    }
    if (message.trustLevel !== undefined) {
      obj.trustLevel = Fraction.toJSON(message.trustLevel);
    }
    if (message.trustingPeriod !== undefined) {
      obj.trustingPeriod = Duration.toJSON(message.trustingPeriod);
    }
    if (message.unbondingPeriod !== undefined) {
      obj.unbondingPeriod = Duration.toJSON(message.unbondingPeriod);
    }
    if (message.maxClockDrift !== undefined) {
      obj.maxClockDrift = Duration.toJSON(message.maxClockDrift);
    }
    if (message.frozenHeight !== undefined) {
      obj.frozenHeight = Height.toJSON(message.frozenHeight);
    }
    if (message.latestHeight !== undefined) {
      obj.latestHeight = Height.toJSON(message.latestHeight);
    }
    if (message.proofSpecs?.length) {
      obj.proofSpecs = message.proofSpecs.map((e) => ProofSpec.toJSON(e));
    }
    if (message.upgradePath?.length) {
      obj.upgradePath = message.upgradePath;
    }
    if (message.allowUpdateAfterExpiry !== undefined) {
      obj.allowUpdateAfterExpiry = message.allowUpdateAfterExpiry;
    }
    if (message.allowUpdateAfterMisbehaviour !== undefined) {
      obj.allowUpdateAfterMisbehaviour = message.allowUpdateAfterMisbehaviour;
    }
    if (message.lcType !== undefined) {
      obj.lcType = message.lcType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClientState>, I>>(base?: I): ClientState {
    return ClientState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientState>, I>>(object: I): ClientState {
    const message = createBaseClientState();
    message.chainId = object.chainId ?? "";
    message.trustLevel = (object.trustLevel !== undefined && object.trustLevel !== null)
      ? Fraction.fromPartial(object.trustLevel)
      : undefined;
    message.trustingPeriod = (object.trustingPeriod !== undefined && object.trustingPeriod !== null)
      ? Duration.fromPartial(object.trustingPeriod)
      : undefined;
    message.unbondingPeriod = (object.unbondingPeriod !== undefined && object.unbondingPeriod !== null)
      ? Duration.fromPartial(object.unbondingPeriod)
      : undefined;
    message.maxClockDrift = (object.maxClockDrift !== undefined && object.maxClockDrift !== null)
      ? Duration.fromPartial(object.maxClockDrift)
      : undefined;
    message.frozenHeight = (object.frozenHeight !== undefined && object.frozenHeight !== null)
      ? Height.fromPartial(object.frozenHeight)
      : undefined;
    message.latestHeight = (object.latestHeight !== undefined && object.latestHeight !== null)
      ? Height.fromPartial(object.latestHeight)
      : undefined;
    message.proofSpecs = object.proofSpecs?.map((e) => ProofSpec.fromPartial(e)) || [];
    message.upgradePath = object.upgradePath?.map((e) => e) || [];
    message.allowUpdateAfterExpiry = object.allowUpdateAfterExpiry ?? false;
    message.allowUpdateAfterMisbehaviour = object.allowUpdateAfterMisbehaviour ?? false;
    message.lcType = object.lcType ?? "";
    return message;
  },
};

function createBaseConsensusState(): ConsensusState {
  return { timestamp: undefined, root: undefined, nextValidatorsHash: new Uint8Array(0), lcType: "" };
}

export const ConsensusState: MessageFns<ConsensusState> = {
  encode(message: ConsensusState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestamp !== undefined) {
      Timestamp.encode(message.timestamp, writer.uint32(10).fork()).join();
    }
    if (message.root !== undefined) {
      MerkleRoot.encode(message.root, writer.uint32(18).fork()).join();
    }
    if (message.nextValidatorsHash.length !== 0) {
      writer.uint32(26).bytes(message.nextValidatorsHash);
    }
    if (message.lcType !== "") {
      writer.uint32(34).string(message.lcType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConsensusState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseConsensusState();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.timestamp = Timestamp.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.root = MerkleRoot.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.nextValidatorsHash = reader.bytes();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.lcType = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ConsensusState {
    return {
      timestamp: isSet(object.timestamp) ? fromJsonTimestamp(object.timestamp) : undefined,
      root: isSet(object.root) ? MerkleRoot.fromJSON(object.root) : undefined,
      nextValidatorsHash: isSet(object.nextValidatorsHash)
        ? bytesFromBase64(object.nextValidatorsHash)
        : isSet(object.next_validators_hash)
        ? bytesFromBase64(object.next_validators_hash)
        : new Uint8Array(0),
      lcType: isSet(object.lcType)
        ? globalThis.String(object.lcType)
        : isSet(object.lc_type)
        ? globalThis.String(object.lc_type)
        : "",
    };
  },

  toJSON(message: ConsensusState): unknown {
    const obj: any = {};
    if (message.timestamp !== undefined) {
      obj.timestamp = fromTimestamp(message.timestamp).toISOString();
    }
    if (message.root !== undefined) {
      obj.root = MerkleRoot.toJSON(message.root);
    }
    if (message.nextValidatorsHash !== undefined) {
      obj.nextValidatorsHash = base64FromBytes(message.nextValidatorsHash);
    }
    if (message.lcType !== undefined) {
      obj.lcType = message.lcType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConsensusState>, I>>(base?: I): ConsensusState {
    return ConsensusState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConsensusState>, I>>(object: I): ConsensusState {
    const message = createBaseConsensusState();
    message.timestamp = (object.timestamp !== undefined && object.timestamp !== null)
      ? Timestamp.fromPartial(object.timestamp)
      : undefined;
    message.root = (object.root !== undefined && object.root !== null)
      ? MerkleRoot.fromPartial(object.root)
      : undefined;
    message.nextValidatorsHash = object.nextValidatorsHash ?? new Uint8Array(0);
    message.lcType = object.lcType ?? "";
    return message;
  },
};

function createBaseMisbehaviour(): Misbehaviour {
  return { clientId: "", header1: undefined, header2: undefined };
}

export const Misbehaviour: MessageFns<Misbehaviour> = {
  encode(message: Misbehaviour, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientId !== "") {
      writer.uint32(10).string(message.clientId);
    }
    if (message.header1 !== undefined) {
      Header.encode(message.header1, writer.uint32(18).fork()).join();
    }
    if (message.header2 !== undefined) {
      Header.encode(message.header2, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Misbehaviour {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMisbehaviour();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.clientId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.header1 = Header.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.header2 = Header.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Misbehaviour {
    return {
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : "",
      header1: isSet(object.header1)
        ? Header.fromJSON(object.header1)
        : isSet(object.header_1)
        ? Header.fromJSON(object.header_1)
        : undefined,
      header2: isSet(object.header2)
        ? Header.fromJSON(object.header2)
        : isSet(object.header_2)
        ? Header.fromJSON(object.header_2)
        : undefined,
    };
  },

  toJSON(message: Misbehaviour): unknown {
    const obj: any = {};
    if (message.clientId !== undefined) {
      obj.clientId = message.clientId;
    }
    if (message.header1 !== undefined) {
      obj.header1 = Header.toJSON(message.header1);
    }
    if (message.header2 !== undefined) {
      obj.header2 = Header.toJSON(message.header2);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Misbehaviour>, I>>(base?: I): Misbehaviour {
    return Misbehaviour.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Misbehaviour>, I>>(object: I): Misbehaviour {
    const message = createBaseMisbehaviour();
    message.clientId = object.clientId ?? "";
    message.header1 = (object.header1 !== undefined && object.header1 !== null)
      ? Header.fromPartial(object.header1)
      : undefined;
    message.header2 = (object.header2 !== undefined && object.header2 !== null)
      ? Header.fromPartial(object.header2)
      : undefined;
    return message;
  },
};

function createBaseHeader(): Header {
  return { signedHeader: undefined, validatorSet: undefined, trustedHeight: undefined, trustedValidators: undefined };
}

export const Header: MessageFns<Header> = {
  encode(message: Header, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signedHeader !== undefined) {
      SignedHeader.encode(message.signedHeader, writer.uint32(10).fork()).join();
    }
    if (message.validatorSet !== undefined) {
      ValidatorSet.encode(message.validatorSet, writer.uint32(18).fork()).join();
    }
    if (message.trustedHeight !== undefined) {
      Height.encode(message.trustedHeight, writer.uint32(26).fork()).join();
    }
    if (message.trustedValidators !== undefined) {
      ValidatorSet.encode(message.trustedValidators, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Header {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseHeader();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.signedHeader = SignedHeader.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.validatorSet = ValidatorSet.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.trustedHeight = Height.decode(reader, reader.uint32());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.trustedValidators = ValidatorSet.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Header {
    return {
      signedHeader: isSet(object.signedHeader)
        ? SignedHeader.fromJSON(object.signedHeader)
        : isSet(object.signed_header)
        ? SignedHeader.fromJSON(object.signed_header)
        : undefined,
      validatorSet: isSet(object.validatorSet)
        ? ValidatorSet.fromJSON(object.validatorSet)
        : isSet(object.validator_set)
        ? ValidatorSet.fromJSON(object.validator_set)
        : undefined,
      trustedHeight: isSet(object.trustedHeight)
        ? Height.fromJSON(object.trustedHeight)
        : isSet(object.trusted_height)
        ? Height.fromJSON(object.trusted_height)
        : undefined,
      trustedValidators: isSet(object.trustedValidators)
        ? ValidatorSet.fromJSON(object.trustedValidators)
        : isSet(object.trusted_validators)
        ? ValidatorSet.fromJSON(object.trusted_validators)
        : undefined,
    };
  },

  toJSON(message: Header): unknown {
    const obj: any = {};
    if (message.signedHeader !== undefined) {
      obj.signedHeader = SignedHeader.toJSON(message.signedHeader);
    }
    if (message.validatorSet !== undefined) {
      obj.validatorSet = ValidatorSet.toJSON(message.validatorSet);
    }
    if (message.trustedHeight !== undefined) {
      obj.trustedHeight = Height.toJSON(message.trustedHeight);
    }
    if (message.trustedValidators !== undefined) {
      obj.trustedValidators = ValidatorSet.toJSON(message.trustedValidators);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Header>, I>>(base?: I): Header {
    return Header.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Header>, I>>(object: I): Header {
    const message = createBaseHeader();
    message.signedHeader = (object.signedHeader !== undefined && object.signedHeader !== null)
      ? SignedHeader.fromPartial(object.signedHeader)
      : undefined;
    message.validatorSet = (object.validatorSet !== undefined && object.validatorSet !== null)
      ? ValidatorSet.fromPartial(object.validatorSet)
      : undefined;
    message.trustedHeight = (object.trustedHeight !== undefined && object.trustedHeight !== null)
      ? Height.fromPartial(object.trustedHeight)
      : undefined;
    message.trustedValidators = (object.trustedValidators !== undefined && object.trustedValidators !== null)
      ? ValidatorSet.fromPartial(object.trustedValidators)
      : undefined;
    return message;
  },
};

function createBaseBlock(): Block {
  return { header: undefined, data: undefined, lastCommit: undefined };
}

export const Block: MessageFns<Block> = {
  encode(message: Block, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.header !== undefined) {
      GnoHeader.encode(message.header, writer.uint32(10).fork()).join();
    }
    if (message.data !== undefined) {
      Data.encode(message.data, writer.uint32(18).fork()).join();
    }
    if (message.lastCommit !== undefined) {
      Commit.encode(message.lastCommit, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Block {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBlock();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.header = GnoHeader.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.data = Data.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.lastCommit = Commit.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Block {
    return {
      header: isSet(object.header) ? GnoHeader.fromJSON(object.header) : undefined,
      data: isSet(object.data) ? Data.fromJSON(object.data) : undefined,
      lastCommit: isSet(object.lastCommit)
        ? Commit.fromJSON(object.lastCommit)
        : isSet(object.last_commit)
        ? Commit.fromJSON(object.last_commit)
        : undefined,
    };
  },

  toJSON(message: Block): unknown {
    const obj: any = {};
    if (message.header !== undefined) {
      obj.header = GnoHeader.toJSON(message.header);
    }
    if (message.data !== undefined) {
      obj.data = Data.toJSON(message.data);
    }
    if (message.lastCommit !== undefined) {
      obj.lastCommit = Commit.toJSON(message.lastCommit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Block>, I>>(base?: I): Block {
    return Block.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Block>, I>>(object: I): Block {
    const message = createBaseBlock();
    message.header = (object.header !== undefined && object.header !== null)
      ? GnoHeader.fromPartial(object.header)
      : undefined;
    message.data = (object.data !== undefined && object.data !== null) ? Data.fromPartial(object.data) : undefined;
    message.lastCommit = (object.lastCommit !== undefined && object.lastCommit !== null)
      ? Commit.fromPartial(object.lastCommit)
      : undefined;
    return message;
  },
};

function createBaseGnoHeader(): GnoHeader {
  return {
    version: "",
    chainId: "",
    height: 0n,
    time: undefined,
    numTxs: 0n,
    totalTxs: 0n,
    appVersion: "",
    lastBlockId: undefined,
    lastCommitHash: new Uint8Array(0),
    dataHash: new Uint8Array(0),
    validatorsHash: new Uint8Array(0),
    nextValidatorsHash: new Uint8Array(0),
    consensusHash: new Uint8Array(0),
    appHash: new Uint8Array(0),
    lastResultsHash: new Uint8Array(0),
    proposerAddress: "",
  };
}

export const GnoHeader: MessageFns<GnoHeader> = {
  encode(message: GnoHeader, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version !== "") {
      writer.uint32(10).string(message.version);
    }
    if (message.chainId !== "") {
      writer.uint32(18).string(message.chainId);
    }
    if (message.height !== 0n) {
      if (BigInt.asIntN(64, message.height) !== message.height) {
        throw new globalThis.Error("value provided for field message.height of type sint64 too large");
      }
      writer.uint32(24).sint64(message.height);
    }
    if (message.time !== undefined) {
      Timestamp.encode(message.time, writer.uint32(34).fork()).join();
    }
    if (message.numTxs !== 0n) {
      if (BigInt.asIntN(64, message.numTxs) !== message.numTxs) {
        throw new globalThis.Error("value provided for field message.numTxs of type sint64 too large");
      }
      writer.uint32(40).sint64(message.numTxs);
    }
    if (message.totalTxs !== 0n) {
      if (BigInt.asIntN(64, message.totalTxs) !== message.totalTxs) {
        throw new globalThis.Error("value provided for field message.totalTxs of type sint64 too large");
      }
      writer.uint32(48).sint64(message.totalTxs);
    }
    if (message.appVersion !== "") {
      writer.uint32(58).string(message.appVersion);
    }
    if (message.lastBlockId !== undefined) {
      BlockID.encode(message.lastBlockId, writer.uint32(66).fork()).join();
    }
    if (message.lastCommitHash.length !== 0) {
      writer.uint32(74).bytes(message.lastCommitHash);
    }
    if (message.dataHash.length !== 0) {
      writer.uint32(82).bytes(message.dataHash);
    }
    if (message.validatorsHash.length !== 0) {
      writer.uint32(90).bytes(message.validatorsHash);
    }
    if (message.nextValidatorsHash.length !== 0) {
      writer.uint32(98).bytes(message.nextValidatorsHash);
    }
    if (message.consensusHash.length !== 0) {
      writer.uint32(106).bytes(message.consensusHash);
    }
    if (message.appHash.length !== 0) {
      writer.uint32(114).bytes(message.appHash);
    }
    if (message.lastResultsHash.length !== 0) {
      writer.uint32(122).bytes(message.lastResultsHash);
    }
    if (message.proposerAddress !== "") {
      writer.uint32(130).string(message.proposerAddress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GnoHeader {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGnoHeader();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.version = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.chainId = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.height = reader.sint64() as bigint;
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.time = Timestamp.decode(reader, reader.uint32());
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.numTxs = reader.sint64() as bigint;
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.totalTxs = reader.sint64() as bigint;
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.appVersion = reader.string();
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.lastBlockId = BlockID.decode(reader, reader.uint32());
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.lastCommitHash = reader.bytes();
            continue;
          }
          case 10: {
            if (tag !== 82) {
              break;
            }

            message.dataHash = reader.bytes();
            continue;
          }
          case 11: {
            if (tag !== 90) {
              break;
            }

            message.validatorsHash = reader.bytes();
            continue;
          }
          case 12: {
            if (tag !== 98) {
              break;
            }

            message.nextValidatorsHash = reader.bytes();
            continue;
          }
          case 13: {
            if (tag !== 106) {
              break;
            }

            message.consensusHash = reader.bytes();
            continue;
          }
          case 14: {
            if (tag !== 114) {
              break;
            }

            message.appHash = reader.bytes();
            continue;
          }
          case 15: {
            if (tag !== 122) {
              break;
            }

            message.lastResultsHash = reader.bytes();
            continue;
          }
          case 16: {
            if (tag !== 130) {
              break;
            }

            message.proposerAddress = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): GnoHeader {
    return {
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      chainId: isSet(object.chainId)
        ? globalThis.String(object.chainId)
        : isSet(object.chain_id)
        ? globalThis.String(object.chain_id)
        : "",
      height: isSet(object.height) ? BigInt(object.height) : 0n,
      time: isSet(object.time) ? fromJsonTimestamp(object.time) : undefined,
      numTxs: isSet(object.numTxs) ? BigInt(object.numTxs) : isSet(object.num_txs) ? BigInt(object.num_txs) : 0n,
      totalTxs: isSet(object.totalTxs)
        ? BigInt(object.totalTxs)
        : isSet(object.total_txs)
        ? BigInt(object.total_txs)
        : 0n,
      appVersion: isSet(object.appVersion)
        ? globalThis.String(object.appVersion)
        : isSet(object.app_version)
        ? globalThis.String(object.app_version)
        : "",
      lastBlockId: isSet(object.lastBlockId)
        ? BlockID.fromJSON(object.lastBlockId)
        : isSet(object.last_block_id)
        ? BlockID.fromJSON(object.last_block_id)
        : undefined,
      lastCommitHash: isSet(object.lastCommitHash)
        ? bytesFromBase64(object.lastCommitHash)
        : isSet(object.last_commit_hash)
        ? bytesFromBase64(object.last_commit_hash)
        : new Uint8Array(0),
      dataHash: isSet(object.dataHash)
        ? bytesFromBase64(object.dataHash)
        : isSet(object.data_hash)
        ? bytesFromBase64(object.data_hash)
        : new Uint8Array(0),
      validatorsHash: isSet(object.validatorsHash)
        ? bytesFromBase64(object.validatorsHash)
        : isSet(object.validators_hash)
        ? bytesFromBase64(object.validators_hash)
        : new Uint8Array(0),
      nextValidatorsHash: isSet(object.nextValidatorsHash)
        ? bytesFromBase64(object.nextValidatorsHash)
        : isSet(object.next_validators_hash)
        ? bytesFromBase64(object.next_validators_hash)
        : new Uint8Array(0),
      consensusHash: isSet(object.consensusHash)
        ? bytesFromBase64(object.consensusHash)
        : isSet(object.consensus_hash)
        ? bytesFromBase64(object.consensus_hash)
        : new Uint8Array(0),
      appHash: isSet(object.appHash)
        ? bytesFromBase64(object.appHash)
        : isSet(object.app_hash)
        ? bytesFromBase64(object.app_hash)
        : new Uint8Array(0),
      lastResultsHash: isSet(object.lastResultsHash)
        ? bytesFromBase64(object.lastResultsHash)
        : isSet(object.last_results_hash)
        ? bytesFromBase64(object.last_results_hash)
        : new Uint8Array(0),
      proposerAddress: isSet(object.proposerAddress)
        ? globalThis.String(object.proposerAddress)
        : isSet(object.proposer_address)
        ? globalThis.String(object.proposer_address)
        : "",
    };
  },

  toJSON(message: GnoHeader): unknown {
    const obj: any = {};
    if (message.version !== undefined) {
      obj.version = message.version;
    }
    if (message.chainId !== undefined) {
      obj.chainId = message.chainId;
    }
    if (message.height !== undefined) {
      obj.height = message.height.toString();
    }
    if (message.time !== undefined) {
      obj.time = fromTimestamp(message.time).toISOString();
    }
    if (message.numTxs !== undefined) {
      obj.numTxs = message.numTxs.toString();
    }
    if (message.totalTxs !== undefined) {
      obj.totalTxs = message.totalTxs.toString();
    }
    if (message.appVersion !== undefined) {
      obj.appVersion = message.appVersion;
    }
    if (message.lastBlockId !== undefined) {
      obj.lastBlockId = BlockID.toJSON(message.lastBlockId);
    }
    if (message.lastCommitHash !== undefined) {
      obj.lastCommitHash = base64FromBytes(message.lastCommitHash);
    }
    if (message.dataHash !== undefined) {
      obj.dataHash = base64FromBytes(message.dataHash);
    }
    if (message.validatorsHash !== undefined) {
      obj.validatorsHash = base64FromBytes(message.validatorsHash);
    }
    if (message.nextValidatorsHash !== undefined) {
      obj.nextValidatorsHash = base64FromBytes(message.nextValidatorsHash);
    }
    if (message.consensusHash !== undefined) {
      obj.consensusHash = base64FromBytes(message.consensusHash);
    }
    if (message.appHash !== undefined) {
      obj.appHash = base64FromBytes(message.appHash);
    }
    if (message.lastResultsHash !== undefined) {
      obj.lastResultsHash = base64FromBytes(message.lastResultsHash);
    }
    if (message.proposerAddress !== undefined) {
      obj.proposerAddress = message.proposerAddress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GnoHeader>, I>>(base?: I): GnoHeader {
    return GnoHeader.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GnoHeader>, I>>(object: I): GnoHeader {
    const message = createBaseGnoHeader();
    message.version = object.version ?? "";
    message.chainId = object.chainId ?? "";
    message.height = (object.height !== undefined && object.height !== null) ? BigInt(object.height) : 0n;
    message.time = (object.time !== undefined && object.time !== null) ? Timestamp.fromPartial(object.time) : undefined;
    message.numTxs = (object.numTxs !== undefined && object.numTxs !== null) ? BigInt(object.numTxs) : 0n;
    message.totalTxs = (object.totalTxs !== undefined && object.totalTxs !== null) ? BigInt(object.totalTxs) : 0n;
    message.appVersion = object.appVersion ?? "";
    message.lastBlockId = (object.lastBlockId !== undefined && object.lastBlockId !== null)
      ? BlockID.fromPartial(object.lastBlockId)
      : undefined;
    message.lastCommitHash = object.lastCommitHash ?? new Uint8Array(0);
    message.dataHash = object.dataHash ?? new Uint8Array(0);
    message.validatorsHash = object.validatorsHash ?? new Uint8Array(0);
    message.nextValidatorsHash = object.nextValidatorsHash ?? new Uint8Array(0);
    message.consensusHash = object.consensusHash ?? new Uint8Array(0);
    message.appHash = object.appHash ?? new Uint8Array(0);
    message.lastResultsHash = object.lastResultsHash ?? new Uint8Array(0);
    message.proposerAddress = object.proposerAddress ?? "";
    return message;
  },
};

function createBaseData(): Data {
  return { txs: [] };
}

export const Data: MessageFns<Data> = {
  encode(message: Data, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.txs) {
      writer.uint32(10).bytes(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Data {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseData();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.txs.push(reader.bytes());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Data {
    return { txs: globalThis.Array.isArray(object?.txs) ? object.txs.map((e: any) => bytesFromBase64(e)) : [] };
  },

  toJSON(message: Data): unknown {
    const obj: any = {};
    if (message.txs?.length) {
      obj.txs = message.txs.map((e) => base64FromBytes(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Data>, I>>(base?: I): Data {
    return Data.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Data>, I>>(object: I): Data {
    const message = createBaseData();
    message.txs = object.txs?.map((e) => e) || [];
    return message;
  },
};

function createBaseCommit(): Commit {
  return { blockId: undefined, precommits: [] };
}

export const Commit: MessageFns<Commit> = {
  encode(message: Commit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.blockId !== undefined) {
      BlockID.encode(message.blockId, writer.uint32(10).fork()).join();
    }
    for (const v of message.precommits) {
      CommitSig.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Commit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCommit();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.blockId = BlockID.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.precommits.push(CommitSig.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Commit {
    return {
      blockId: isSet(object.blockId)
        ? BlockID.fromJSON(object.blockId)
        : isSet(object.block_id)
        ? BlockID.fromJSON(object.block_id)
        : undefined,
      precommits: globalThis.Array.isArray(object?.precommits)
        ? object.precommits.map((e: any) => CommitSig.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Commit): unknown {
    const obj: any = {};
    if (message.blockId !== undefined) {
      obj.blockId = BlockID.toJSON(message.blockId);
    }
    if (message.precommits?.length) {
      obj.precommits = message.precommits.map((e) => CommitSig.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Commit>, I>>(base?: I): Commit {
    return Commit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Commit>, I>>(object: I): Commit {
    const message = createBaseCommit();
    message.blockId = (object.blockId !== undefined && object.blockId !== null)
      ? BlockID.fromPartial(object.blockId)
      : undefined;
    message.precommits = object.precommits?.map((e) => CommitSig.fromPartial(e)) || [];
    return message;
  },
};

function createBaseBlockID(): BlockID {
  return { hash: new Uint8Array(0), partsHeader: undefined };
}

export const BlockID: MessageFns<BlockID> = {
  encode(message: BlockID, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hash.length !== 0) {
      writer.uint32(10).bytes(message.hash);
    }
    if (message.partsHeader !== undefined) {
      PartSetHeader.encode(message.partsHeader, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BlockID {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBlockID();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.hash = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.partsHeader = PartSetHeader.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): BlockID {
    return {
      hash: isSet(object.hash) ? bytesFromBase64(object.hash) : new Uint8Array(0),
      partsHeader: isSet(object.parts)
        ? PartSetHeader.fromJSON(object.parts)
        : isSet(object.parts_header)
        ? PartSetHeader.fromJSON(object.parts_header)
        : undefined,
    };
  },

  toJSON(message: BlockID): unknown {
    const obj: any = {};
    if (message.hash !== undefined) {
      obj.hash = base64FromBytes(message.hash);
    }
    if (message.partsHeader !== undefined) {
      obj.parts = PartSetHeader.toJSON(message.partsHeader);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BlockID>, I>>(base?: I): BlockID {
    return BlockID.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BlockID>, I>>(object: I): BlockID {
    const message = createBaseBlockID();
    message.hash = object.hash ?? new Uint8Array(0);
    message.partsHeader = (object.partsHeader !== undefined && object.partsHeader !== null)
      ? PartSetHeader.fromPartial(object.partsHeader)
      : undefined;
    return message;
  },
};

function createBaseSignedHeader(): SignedHeader {
  return { header: undefined, commit: undefined };
}

export const SignedHeader: MessageFns<SignedHeader> = {
  encode(message: SignedHeader, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.header !== undefined) {
      GnoHeader.encode(message.header, writer.uint32(10).fork()).join();
    }
    if (message.commit !== undefined) {
      Commit.encode(message.commit, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignedHeader {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSignedHeader();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.header = GnoHeader.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.commit = Commit.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): SignedHeader {
    return {
      header: isSet(object.header) ? GnoHeader.fromJSON(object.header) : undefined,
      commit: isSet(object.commit) ? Commit.fromJSON(object.commit) : undefined,
    };
  },

  toJSON(message: SignedHeader): unknown {
    const obj: any = {};
    if (message.header !== undefined) {
      obj.header = GnoHeader.toJSON(message.header);
    }
    if (message.commit !== undefined) {
      obj.commit = Commit.toJSON(message.commit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SignedHeader>, I>>(base?: I): SignedHeader {
    return SignedHeader.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignedHeader>, I>>(object: I): SignedHeader {
    const message = createBaseSignedHeader();
    message.header = (object.header !== undefined && object.header !== null)
      ? GnoHeader.fromPartial(object.header)
      : undefined;
    message.commit = (object.commit !== undefined && object.commit !== null)
      ? Commit.fromPartial(object.commit)
      : undefined;
    return message;
  },
};

function createBaseLightBlock(): LightBlock {
  return { signedHeader: undefined, validatorSet: undefined };
}

export const LightBlock: MessageFns<LightBlock> = {
  encode(message: LightBlock, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signedHeader !== undefined) {
      SignedHeader.encode(message.signedHeader, writer.uint32(10).fork()).join();
    }
    if (message.validatorSet !== undefined) {
      ValidatorSet.encode(message.validatorSet, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LightBlock {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLightBlock();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.signedHeader = SignedHeader.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.validatorSet = ValidatorSet.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): LightBlock {
    return {
      signedHeader: isSet(object.signedHeader)
        ? SignedHeader.fromJSON(object.signedHeader)
        : isSet(object.signed_header)
        ? SignedHeader.fromJSON(object.signed_header)
        : undefined,
      validatorSet: isSet(object.validatorSet)
        ? ValidatorSet.fromJSON(object.validatorSet)
        : isSet(object.validator_set)
        ? ValidatorSet.fromJSON(object.validator_set)
        : undefined,
    };
  },

  toJSON(message: LightBlock): unknown {
    const obj: any = {};
    if (message.signedHeader !== undefined) {
      obj.signedHeader = SignedHeader.toJSON(message.signedHeader);
    }
    if (message.validatorSet !== undefined) {
      obj.validatorSet = ValidatorSet.toJSON(message.validatorSet);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LightBlock>, I>>(base?: I): LightBlock {
    return LightBlock.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LightBlock>, I>>(object: I): LightBlock {
    const message = createBaseLightBlock();
    message.signedHeader = (object.signedHeader !== undefined && object.signedHeader !== null)
      ? SignedHeader.fromPartial(object.signedHeader)
      : undefined;
    message.validatorSet = (object.validatorSet !== undefined && object.validatorSet !== null)
      ? ValidatorSet.fromPartial(object.validatorSet)
      : undefined;
    return message;
  },
};

function createBaseCommitSig(): CommitSig {
  return {
    type: 0,
    height: 0n,
    round: 0n,
    blockId: undefined,
    timestamp: undefined,
    validatorAddress: "",
    validatorIndex: 0n,
    signature: new Uint8Array(0),
  };
}

export const CommitSig: MessageFns<CommitSig> = {
  encode(message: CommitSig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).uint32(message.type);
    }
    if (message.height !== 0n) {
      if (BigInt.asIntN(64, message.height) !== message.height) {
        throw new globalThis.Error("value provided for field message.height of type sint64 too large");
      }
      writer.uint32(16).sint64(message.height);
    }
    if (message.round !== 0n) {
      if (BigInt.asIntN(64, message.round) !== message.round) {
        throw new globalThis.Error("value provided for field message.round of type sint64 too large");
      }
      writer.uint32(24).sint64(message.round);
    }
    if (message.blockId !== undefined) {
      BlockID.encode(message.blockId, writer.uint32(34).fork()).join();
    }
    if (message.timestamp !== undefined) {
      Timestamp.encode(message.timestamp, writer.uint32(42).fork()).join();
    }
    if (message.validatorAddress !== "") {
      writer.uint32(50).string(message.validatorAddress);
    }
    if (message.validatorIndex !== 0n) {
      if (BigInt.asIntN(64, message.validatorIndex) !== message.validatorIndex) {
        throw new globalThis.Error("value provided for field message.validatorIndex of type sint64 too large");
      }
      writer.uint32(56).sint64(message.validatorIndex);
    }
    if (message.signature.length !== 0) {
      writer.uint32(66).bytes(message.signature);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CommitSig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCommitSig();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.type = reader.uint32();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.height = reader.sint64() as bigint;
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.round = reader.sint64() as bigint;
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.blockId = BlockID.decode(reader, reader.uint32());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.timestamp = Timestamp.decode(reader, reader.uint32());
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.validatorAddress = reader.string();
            continue;
          }
          case 7: {
            if (tag !== 56) {
              break;
            }

            message.validatorIndex = reader.sint64() as bigint;
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.signature = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): CommitSig {
    return {
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
      height: isSet(object.height) ? BigInt(object.height) : 0n,
      round: isSet(object.round) ? BigInt(object.round) : 0n,
      blockId: isSet(object.blockId)
        ? BlockID.fromJSON(object.blockId)
        : isSet(object.block_id)
        ? BlockID.fromJSON(object.block_id)
        : undefined,
      timestamp: isSet(object.timestamp) ? fromJsonTimestamp(object.timestamp) : undefined,
      validatorAddress: isSet(object.validatorAddress)
        ? globalThis.String(object.validatorAddress)
        : isSet(object.validator_address)
        ? globalThis.String(object.validator_address)
        : "",
      validatorIndex: isSet(object.validatorIndex)
        ? BigInt(object.validatorIndex)
        : isSet(object.validator_index)
        ? BigInt(object.validator_index)
        : 0n,
      signature: isSet(object.signature) ? bytesFromBase64(object.signature) : new Uint8Array(0),
    };
  },

  toJSON(message: CommitSig): unknown {
    const obj: any = {};
    if (message.type !== undefined) {
      obj.type = Math.round(message.type);
    }
    if (message.height !== undefined) {
      obj.height = message.height.toString();
    }
    if (message.round !== undefined) {
      obj.round = message.round.toString();
    }
    if (message.blockId !== undefined) {
      obj.blockId = BlockID.toJSON(message.blockId);
    }
    if (message.timestamp !== undefined) {
      obj.timestamp = fromTimestamp(message.timestamp).toISOString();
    }
    if (message.validatorAddress !== undefined) {
      obj.validatorAddress = message.validatorAddress;
    }
    if (message.validatorIndex !== undefined) {
      obj.validatorIndex = message.validatorIndex.toString();
    }
    if (message.signature !== undefined) {
      obj.signature = base64FromBytes(message.signature);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CommitSig>, I>>(base?: I): CommitSig {
    return CommitSig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommitSig>, I>>(object: I): CommitSig {
    const message = createBaseCommitSig();
    message.type = object.type ?? 0;
    message.height = (object.height !== undefined && object.height !== null) ? BigInt(object.height) : 0n;
    message.round = (object.round !== undefined && object.round !== null) ? BigInt(object.round) : 0n;
    message.blockId = (object.blockId !== undefined && object.blockId !== null)
      ? BlockID.fromPartial(object.blockId)
      : undefined;
    message.timestamp = (object.timestamp !== undefined && object.timestamp !== null)
      ? Timestamp.fromPartial(object.timestamp)
      : undefined;
    message.validatorAddress = object.validatorAddress ?? "";
    message.validatorIndex = (object.validatorIndex !== undefined && object.validatorIndex !== null)
      ? BigInt(object.validatorIndex)
      : 0n;
    message.signature = object.signature ?? new Uint8Array(0);
    return message;
  },
};

function createBaseVote(): Vote {
  return {
    type: 0,
    height: 0n,
    round: 0n,
    blockId: undefined,
    timestamp: undefined,
    validatorAddress: "",
    validatorIndex: 0n,
    signature: new Uint8Array(0),
  };
}

export const Vote: MessageFns<Vote> = {
  encode(message: Vote, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).uint32(message.type);
    }
    if (message.height !== 0n) {
      if (BigInt.asIntN(64, message.height) !== message.height) {
        throw new globalThis.Error("value provided for field message.height of type sint64 too large");
      }
      writer.uint32(16).sint64(message.height);
    }
    if (message.round !== 0n) {
      if (BigInt.asIntN(64, message.round) !== message.round) {
        throw new globalThis.Error("value provided for field message.round of type sint64 too large");
      }
      writer.uint32(24).sint64(message.round);
    }
    if (message.blockId !== undefined) {
      BlockID.encode(message.blockId, writer.uint32(34).fork()).join();
    }
    if (message.timestamp !== undefined) {
      Timestamp.encode(message.timestamp, writer.uint32(42).fork()).join();
    }
    if (message.validatorAddress !== "") {
      writer.uint32(50).string(message.validatorAddress);
    }
    if (message.validatorIndex !== 0n) {
      if (BigInt.asIntN(64, message.validatorIndex) !== message.validatorIndex) {
        throw new globalThis.Error("value provided for field message.validatorIndex of type sint64 too large");
      }
      writer.uint32(56).sint64(message.validatorIndex);
    }
    if (message.signature.length !== 0) {
      writer.uint32(66).bytes(message.signature);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Vote {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseVote();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.type = reader.uint32();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.height = reader.sint64() as bigint;
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.round = reader.sint64() as bigint;
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.blockId = BlockID.decode(reader, reader.uint32());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.timestamp = Timestamp.decode(reader, reader.uint32());
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.validatorAddress = reader.string();
            continue;
          }
          case 7: {
            if (tag !== 56) {
              break;
            }

            message.validatorIndex = reader.sint64() as bigint;
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.signature = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Vote {
    return {
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
      height: isSet(object.height) ? BigInt(object.height) : 0n,
      round: isSet(object.round) ? BigInt(object.round) : 0n,
      blockId: isSet(object.blockId)
        ? BlockID.fromJSON(object.blockId)
        : isSet(object.block_id)
        ? BlockID.fromJSON(object.block_id)
        : undefined,
      timestamp: isSet(object.timestamp) ? fromJsonTimestamp(object.timestamp) : undefined,
      validatorAddress: isSet(object.validatorAddress)
        ? globalThis.String(object.validatorAddress)
        : isSet(object.validator_address)
        ? globalThis.String(object.validator_address)
        : "",
      validatorIndex: isSet(object.validatorIndex)
        ? BigInt(object.validatorIndex)
        : isSet(object.validator_index)
        ? BigInt(object.validator_index)
        : 0n,
      signature: isSet(object.signature) ? bytesFromBase64(object.signature) : new Uint8Array(0),
    };
  },

  toJSON(message: Vote): unknown {
    const obj: any = {};
    if (message.type !== undefined) {
      obj.type = Math.round(message.type);
    }
    if (message.height !== undefined) {
      obj.height = message.height.toString();
    }
    if (message.round !== undefined) {
      obj.round = message.round.toString();
    }
    if (message.blockId !== undefined) {
      obj.blockId = BlockID.toJSON(message.blockId);
    }
    if (message.timestamp !== undefined) {
      obj.timestamp = fromTimestamp(message.timestamp).toISOString();
    }
    if (message.validatorAddress !== undefined) {
      obj.validatorAddress = message.validatorAddress;
    }
    if (message.validatorIndex !== undefined) {
      obj.validatorIndex = message.validatorIndex.toString();
    }
    if (message.signature !== undefined) {
      obj.signature = base64FromBytes(message.signature);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Vote>, I>>(base?: I): Vote {
    return Vote.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Vote>, I>>(object: I): Vote {
    const message = createBaseVote();
    message.type = object.type ?? 0;
    message.height = (object.height !== undefined && object.height !== null) ? BigInt(object.height) : 0n;
    message.round = (object.round !== undefined && object.round !== null) ? BigInt(object.round) : 0n;
    message.blockId = (object.blockId !== undefined && object.blockId !== null)
      ? BlockID.fromPartial(object.blockId)
      : undefined;
    message.timestamp = (object.timestamp !== undefined && object.timestamp !== null)
      ? Timestamp.fromPartial(object.timestamp)
      : undefined;
    message.validatorAddress = object.validatorAddress ?? "";
    message.validatorIndex = (object.validatorIndex !== undefined && object.validatorIndex !== null)
      ? BigInt(object.validatorIndex)
      : 0n;
    message.signature = object.signature ?? new Uint8Array(0);
    return message;
  },
};

function createBasePartSet(): PartSet {
  return {};
}

export const PartSet: MessageFns<PartSet> = {
  encode(_: PartSet, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PartSet {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePartSet();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): PartSet {
    return {};
  },

  toJSON(_: PartSet): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<PartSet>, I>>(base?: I): PartSet {
    return PartSet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PartSet>, I>>(_: I): PartSet {
    const message = createBasePartSet();
    return message;
  },
};

function createBasePartSetHeader(): PartSetHeader {
  return { total: 0n, hash: new Uint8Array(0) };
}

export const PartSetHeader: MessageFns<PartSetHeader> = {
  encode(message: PartSetHeader, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.total !== 0n) {
      if (BigInt.asIntN(64, message.total) !== message.total) {
        throw new globalThis.Error("value provided for field message.total of type sint64 too large");
      }
      writer.uint32(8).sint64(message.total);
    }
    if (message.hash.length !== 0) {
      writer.uint32(18).bytes(message.hash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PartSetHeader {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePartSetHeader();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.total = reader.sint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.hash = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): PartSetHeader {
    return {
      total: isSet(object.total) ? BigInt(object.total) : 0n,
      hash: isSet(object.hash) ? bytesFromBase64(object.hash) : new Uint8Array(0),
    };
  },

  toJSON(message: PartSetHeader): unknown {
    const obj: any = {};
    if (message.total !== undefined) {
      obj.total = message.total.toString();
    }
    if (message.hash !== undefined) {
      obj.hash = base64FromBytes(message.hash);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PartSetHeader>, I>>(base?: I): PartSetHeader {
    return PartSetHeader.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PartSetHeader>, I>>(object: I): PartSetHeader {
    const message = createBasePartSetHeader();
    message.total = (object.total !== undefined && object.total !== null) ? BigInt(object.total) : 0n;
    message.hash = object.hash ?? new Uint8Array(0);
    return message;
  },
};

function createBaseValidator(): Validator {
  return { address: "", pubKey: undefined, votingPower: 0n, proposerPriority: 0n };
}

export const Validator: MessageFns<Validator> = {
  encode(message: Validator, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    if (message.pubKey !== undefined) {
      PublicKey.encode(message.pubKey, writer.uint32(18).fork()).join();
    }
    if (message.votingPower !== 0n) {
      if (BigInt.asIntN(64, message.votingPower) !== message.votingPower) {
        throw new globalThis.Error("value provided for field message.votingPower of type sint64 too large");
      }
      writer.uint32(24).sint64(message.votingPower);
    }
    if (message.proposerPriority !== 0n) {
      if (BigInt.asIntN(64, message.proposerPriority) !== message.proposerPriority) {
        throw new globalThis.Error("value provided for field message.proposerPriority of type sint64 too large");
      }
      writer.uint32(32).sint64(message.proposerPriority);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Validator {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseValidator();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.address = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.pubKey = PublicKey.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.votingPower = reader.sint64() as bigint;
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.proposerPriority = reader.sint64() as bigint;
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Validator {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      pubKey: isSet(object.pubKey)
        ? PublicKey.fromJSON(object.pubKey)
        : isSet(object.pub_key)
        ? PublicKey.fromJSON(object.pub_key)
        : undefined,
      votingPower: isSet(object.votingPower)
        ? BigInt(object.votingPower)
        : isSet(object.voting_power)
        ? BigInt(object.voting_power)
        : 0n,
      proposerPriority: isSet(object.proposerPriority)
        ? BigInt(object.proposerPriority)
        : isSet(object.proposer_priority)
        ? BigInt(object.proposer_priority)
        : 0n,
    };
  },

  toJSON(message: Validator): unknown {
    const obj: any = {};
    if (message.address !== undefined) {
      obj.address = message.address;
    }
    if (message.pubKey !== undefined) {
      obj.pubKey = PublicKey.toJSON(message.pubKey);
    }
    if (message.votingPower !== undefined) {
      obj.votingPower = message.votingPower.toString();
    }
    if (message.proposerPriority !== undefined) {
      obj.proposerPriority = message.proposerPriority.toString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Validator>, I>>(base?: I): Validator {
    return Validator.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Validator>, I>>(object: I): Validator {
    const message = createBaseValidator();
    message.address = object.address ?? "";
    message.pubKey = (object.pubKey !== undefined && object.pubKey !== null)
      ? PublicKey.fromPartial(object.pubKey)
      : undefined;
    message.votingPower = (object.votingPower !== undefined && object.votingPower !== null)
      ? BigInt(object.votingPower)
      : 0n;
    message.proposerPriority = (object.proposerPriority !== undefined && object.proposerPriority !== null)
      ? BigInt(object.proposerPriority)
      : 0n;
    return message;
  },
};

function createBaseValidatorSet(): ValidatorSet {
  return { validators: [], proposer: undefined };
}

export const ValidatorSet: MessageFns<ValidatorSet> = {
  encode(message: ValidatorSet, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.validators) {
      Validator.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.proposer !== undefined) {
      Validator.encode(message.proposer, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidatorSet {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseValidatorSet();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.validators.push(Validator.decode(reader, reader.uint32()));
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.proposer = Validator.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ValidatorSet {
    return {
      validators: globalThis.Array.isArray(object?.validators)
        ? object.validators.map((e: any) => Validator.fromJSON(e))
        : [],
      proposer: isSet(object.proposer) ? Validator.fromJSON(object.proposer) : undefined,
    };
  },

  toJSON(message: ValidatorSet): unknown {
    const obj: any = {};
    if (message.validators?.length) {
      obj.validators = message.validators.map((e) => Validator.toJSON(e));
    }
    if (message.proposer !== undefined) {
      obj.proposer = Validator.toJSON(message.proposer);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidatorSet>, I>>(base?: I): ValidatorSet {
    return ValidatorSet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidatorSet>, I>>(object: I): ValidatorSet {
    const message = createBaseValidatorSet();
    message.validators = object.validators?.map((e) => Validator.fromPartial(e)) || [];
    message.proposer = (object.proposer !== undefined && object.proposer !== null)
      ? Validator.fromPartial(object.proposer)
      : undefined;
    return message;
  },
};

function createBaseFraction(): Fraction {
  return { numerator: 0n, denominator: 0n };
}

export const Fraction: MessageFns<Fraction> = {
  encode(message: Fraction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.numerator !== 0n) {
      if (BigInt.asUintN(64, message.numerator) !== message.numerator) {
        throw new globalThis.Error("value provided for field message.numerator of type uint64 too large");
      }
      writer.uint32(8).uint64(message.numerator);
    }
    if (message.denominator !== 0n) {
      if (BigInt.asUintN(64, message.denominator) !== message.denominator) {
        throw new globalThis.Error("value provided for field message.denominator of type uint64 too large");
      }
      writer.uint32(16).uint64(message.denominator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Fraction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseFraction();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.numerator = reader.uint64() as bigint;
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.denominator = reader.uint64() as bigint;
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Fraction {
    return {
      numerator: isSet(object.numerator) ? BigInt(object.numerator) : 0n,
      denominator: isSet(object.denominator) ? BigInt(object.denominator) : 0n,
    };
  },

  toJSON(message: Fraction): unknown {
    const obj: any = {};
    if (message.numerator !== undefined) {
      obj.numerator = message.numerator.toString();
    }
    if (message.denominator !== undefined) {
      obj.denominator = message.denominator.toString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Fraction>, I>>(base?: I): Fraction {
    return Fraction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Fraction>, I>>(object: I): Fraction {
    const message = createBaseFraction();
    message.numerator = (object.numerator !== undefined && object.numerator !== null) ? BigInt(object.numerator) : 0n;
    message.denominator = (object.denominator !== undefined && object.denominator !== null)
      ? BigInt(object.denominator)
      : 0n;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

type DeepPartial<T> = T extends bigint ? string | number | bigint
  : T extends Builtin ? T : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = BigInt(Math.trunc(date.getTime() / 1_000));
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds.toString()) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Timestamp {
  if (o instanceof globalThis.Date) {
    return toTimestamp(o);
  } else if (typeof o === "string") {
    return toTimestamp(new globalThis.Date(o));
  } else {
    return Timestamp.fromJSON(o);
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
