// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v6.33.4
// source: gno/tm2/bitarray/bitarray.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

/** messages */
export interface BitArray {
  bits: bigint;
  elems: bigint[];
}

function createBaseBitArray(): BitArray {
  return { bits: 0n, elems: [] };
}

export const BitArray: MessageFns<BitArray> = {
  encode(message: BitArray, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bits !== 0n) {
      if (BigInt.asIntN(64, message.bits) !== message.bits) {
        throw new globalThis.Error("value provided for field message.bits of type sint64 too large");
      }
      writer.uint32(8).sint64(message.bits);
    }
    writer.uint32(18).fork();
    for (const v of message.elems) {
      if (BigInt.asUintN(64, v) !== v) {
        throw new globalThis.Error("a value provided in array field elems of type uint64 is too large");
      }
      writer.uint64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BitArray {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBitArray();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.bits = reader.sint64() as bigint;
            continue;
          }
          case 2: {
            if (tag === 16) {
              message.elems.push(reader.uint64() as bigint);

              continue;
            }

            if (tag === 18) {
              const end2 = reader.uint32() + reader.pos;
              while (reader.pos < end2) {
                message.elems.push(reader.uint64() as bigint);
              }

              continue;
            }

            break;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): BitArray {
    return {
      bits: isSet(object.bits) ? BigInt(object.bits) : 0n,
      elems: globalThis.Array.isArray(object?.elems) ? object.elems.map((e: any) => BigInt(e)) : [],
    };
  },

  toJSON(message: BitArray): unknown {
    const obj: any = {};
    if (message.bits !== undefined) {
      obj.bits = message.bits.toString();
    }
    if (message.elems?.length) {
      obj.elems = message.elems.map((e) => e.toString());
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BitArray>, I>>(base?: I): BitArray {
    return BitArray.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BitArray>, I>>(object: I): BitArray {
    const message = createBaseBitArray();
    message.bits = (object.bits !== undefined && object.bits !== null) ? BigInt(object.bits) : 0n;
    message.elems = object.elems?.map((e) => BigInt(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

type DeepPartial<T> = T extends bigint ? string | number | bigint
  : T extends Builtin ? T : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
